cloud:
  aws:
    region:
      static: us-east-1
      auto: false
    stack:
      auto: false
    credentials:
      access-key: AKIASXSUMI76GFHZXB4P
      secret-key: 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
    endpoint:  
      uri: https://sqs.us-east-1.amazonaws.com/188081784828/merxi-queue
      
      
server:
  port: 8443     